export {
  GlobeIcon,
  HandsIcon,
  BuildingIcon,
  BookIcon,
  LocationIcon,
  EmailIcon,
  PhoneIcon,
  ArrowDownIcon,
  ArrowRightIcon,
  MenuIcon,
  CloseIcon,
  FacebookIcon,
  TwitterIcon,
  InstagramIcon,
  LinkedInIcon,
  CalendarIcon,
  UserIcon,
  StarIcon,
  HeartIcon,
  SearchIcon,
  CameraIcon,
  DocumentIcon,
  TrophyIcon,
  TeamIcon,
  LightbulbIcon,
  TargetIcon,
} from './custom-icons';
